### ISSUE TITLE
Rails couldn't find a valid model when using `scope` with `includes`

### ISSUE THREAD

**Issue by DEfusion** [onyxblade/associationist#10]
Firstly ❤️ the idea of this Gem, it's perfect for a need I came across today and a really nice implementation.

On Rails 7.0.4 I've defined the following in my model:

```
include Associationist::Mixin.new(
    name: :surfaced_values,
    scope: lambda() { |entry|
      Properties::Value.joins(:property).where(value_ownable: entry).merge(Property.surfaced)
    },
    type: :collection
  )
```

If I do `Entry.last.surfaced_values` it works as expected. 

However if I do `Entry.includes(:surfaced_values).last` I get this error:

```
Rails couldn't find a valid model for SurfacedValue association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.
```

If I add `class_name: 'Properties::Value'` it gives me the same error.

**Comment by DEfusion** [comment]
I've tried a couple of approaches here, the first was to override `compute_class` in `collection_reflection` like so:

```
def compute_class(name)
  config.class_name&.safe_constantize || super
end
```

That got me a little further by giving me this error:

```
active_record/relation/delegation.rb:110:in `method_missing': undefined method `new_record?' for #<ActiveRecord::Relation [#<Properties::Value
```

The other was by creating a simple `SurfacedValue` model which extended `Properties::Value` which also gave me the same `new_record?` error.

**Comment by DEfusion** [comment]
Ah, I got it working via a `preloader` from the docs it seemed like a `scope` was better suited for the situation and would work. This is what I ended up with:

```
include Associationist::Mixin.new(
    name: :surfaced_values,
    class_name: 'Properties::Value',
    preloader: lambda() { |records|
      values = Properties::Value.joins(:property).where(value_ownable: records).merge(Property.surfaced)
      records.to_h do |r|
        [r, values.filter { |v| v.value_ownable_id == r.id }]
      end
    }
  )
```

Once again thanks for the great gem, just might need to clarify the docs a little on when `scope` is better (or I may have misunderstood).

**Comment by onyxblade** [comment]
Hey @DEfusion, sorry for the late reply.

I think I successfully located why `scope` was not working. However, even if `scope` is working, it'd still introduce n+1 queries because the `scope` is evaluated for each owner record, so `preloader` is still the way to avoid n+1 queries. Good to hear `preloader` works for your case. One downside of `preloader` is that it doesn't work well with through association preloading, and that's the reason I attempted to support `scope`.

It's been a while since I last worked on this, and I've forgot many details... Will come back to this gem later and reconsider what can possibly be improved.

Thanks for the :heart:!

Cheers
